# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccelerometerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorId', models.IntegerField()),
                ('xValue', models.IntegerField()),
                ('yValue', models.IntegerField()),
                ('zValue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('switch', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MicrophoneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorId', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('dataType', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('index', models.IntegerField()),
                ('sensorType', models.CharField(default=None, max_length=30, null=True)),
                ('rgroup', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='snorlax.ReadingGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VelostatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorId', models.IntegerField()),
                ('value', models.IntegerField()),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snorlax.Time')),
            ],
        ),
        migrations.AddField(
            model_name='microphonedata',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snorlax.Time'),
        ),
        migrations.AddField(
            model_name='accelerometerdata',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snorlax.Time'),
        ),
    ]
